consumes:
- application/json
- application/xml
- application/gob
- application/x-gob
definitions:
  Complex:
    description: Complex media type (default view)
    example:
      users:
      - created_at: 1991-05-24T08:22:09Z
        id: 1
        name: test
      - created_at: 1991-05-24T08:22:09Z
        id: 1
        name: test
    properties:
      users:
        $ref: '#/definitions/UserCollection'
    required:
    - users
    title: 'Mediatype identifier: application/vnd.complex+json; view=default'
    type: object
  User:
    description: user (default view)
    example:
      created_at: 1991-05-24T08:22:09Z
      id: 1
      name: test
    properties:
      created_at:
        description: Date of creation
        example: 1991-05-24T08:22:09Z
        format: date-time
        type: string
      id:
        description: ID of user
        example: 1
        format: int64
        type: integer
      name:
        description: Name of user
        example: test
        type: string
    required:
    - id
    - name
    - created_at
    title: 'Mediatype identifier: application/vnd.user+json; view=default'
    type: object
  UserCollection:
    description: UserCollection is the media type for an array of User (default view)
    example:
    - created_at: 1991-05-24T08:22:09Z
      id: 1
      name: test
    - created_at: 1991-05-24T08:22:09Z
      id: 1
      name: test
    items:
      $ref: '#/definitions/User'
    title: 'Mediatype identifier: application/vnd.user+json; type=collection; view=default'
    type: array
host: localhost:8081
info:
  description: sample microservice API with goa
  title: gateway api server
  version: ""
paths:
  /gateway:
    get:
      description: gateway
      operationId: gateway#gateway
      produces:
      - application/vnd.complex+json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/Complex'
      schemes:
      - http
      summary: gateway gateway
      tags:
      - gateway
produces:
- application/json
- application/xml
- application/gob
- application/x-gob
schemes:
- http
swagger: "2.0"
