// Code generated by goagen v1.3.1, DO NOT EDIT.
//
// API "gateway": Application Controllers
//
// Command:
// $ goagen
// --design=github.com/azihsoyn/goa_microservice_sample/gateway/design
// --notest=true
// --notool=true
// --out=$(GOPATH)/src/github.com/azihsoyn/goa_microservice_sample/gateway
// --version=v1.3.1

package app

import (
	"context"
	"github.com/goadesign/goa"
	"net/http"
)

// initService sets up the service encoders, decoders and mux.
func initService(service *goa.Service) {
	// Setup encoders and decoders
	service.Encoder.Register(goa.NewJSONEncoder, "application/json")
	service.Encoder.Register(goa.NewGobEncoder, "application/gob", "application/x-gob")
	service.Encoder.Register(goa.NewXMLEncoder, "application/xml")
	service.Decoder.Register(goa.NewJSONDecoder, "application/json")
	service.Decoder.Register(goa.NewGobDecoder, "application/gob", "application/x-gob")
	service.Decoder.Register(goa.NewXMLDecoder, "application/xml")

	// Setup default encoder and decoder
	service.Encoder.Register(goa.NewJSONEncoder, "*/*")
	service.Decoder.Register(goa.NewJSONDecoder, "*/*")
}

// GatewayController is the controller interface for the Gateway actions.
type GatewayController interface {
	goa.Muxer
	Gateway(*GatewayGatewayContext) error
}

// MountGatewayController "mounts" a Gateway resource controller on the given service.
func MountGatewayController(service *goa.Service, ctrl GatewayController) {
	initService(service)
	var h goa.Handler

	h = func(ctx context.Context, rw http.ResponseWriter, req *http.Request) error {
		// Check if there was an error loading the request
		if err := goa.ContextError(ctx); err != nil {
			return err
		}
		// Build the context
		rctx, err := NewGatewayGatewayContext(ctx, req, service)
		if err != nil {
			return err
		}
		return ctrl.Gateway(rctx)
	}
	service.Mux.Handle("GET", "/gateway", ctrl.MuxHandler("gateway", h, nil))
	service.LogInfo("mount", "ctrl", "Gateway", "action", "Gateway", "route", "GET /gateway")
}
