// Code generated by goagen v1.3.1, DO NOT EDIT.
//
// API "gateway": Application Contexts
//
// Command:
// $ goagen
// --design=github.com/azihsoyn/goa_microservice_sample/gateway/design
// --notest=true
// --notool=true
// --out=$(GOPATH)/src/github.com/azihsoyn/goa_microservice_sample/gateway
// --version=v1.3.1

package app

import (
	"context"
	"github.com/goadesign/goa"
	"net/http"
)

// GatewayGatewayContext provides the gateway gateway action context.
type GatewayGatewayContext struct {
	context.Context
	*goa.ResponseData
	*goa.RequestData
}

// NewGatewayGatewayContext parses the incoming request URL and body, performs validations and creates the
// context used by the gateway controller gateway action.
func NewGatewayGatewayContext(ctx context.Context, r *http.Request, service *goa.Service) (*GatewayGatewayContext, error) {
	var err error
	resp := goa.ContextResponse(ctx)
	resp.Service = service
	req := goa.ContextRequest(ctx)
	req.Request = r
	rctx := GatewayGatewayContext{Context: ctx, ResponseData: resp, RequestData: req}
	return &rctx, err
}

// OK sends a HTTP response with status code 200.
func (ctx *GatewayGatewayContext) OK(r *Complex) error {
	if ctx.ResponseData.Header().Get("Content-Type") == "" {
		ctx.ResponseData.Header().Set("Content-Type", "application/vnd.complex+json")
	}
	return ctx.ResponseData.Service.Send(ctx.Context, 200, r)
}
