// Code generated by goagen v1.3.1, DO NOT EDIT.
//
// API "gateway": Application Media Types
//
// Command:
// $ goagen
// --design=github.com/azihsoyn/goa_microservice_sample/gateway/design
// --notest=true
// --notool=true
// --out=$(GOPATH)/src/github.com/azihsoyn/goa_microservice_sample/gateway
// --version=v1.3.1

package app

import (
	"github.com/azihsoyn/goa_microservice_sample/user_service/app"
	"github.com/goadesign/goa"
	"time"
)

// Complex media type (default view)
//
// Identifier: application/vnd.complex+json; view=default
type Complex struct {
	// list of user
	Users app.UserCollection `form:"users" json:"users" xml:"users"`
}

// Validate validates the Complex media type instance.
func (mt *Complex) Validate() (err error) {
	if mt.Users == nil {
		err = goa.MergeErrors(err, goa.MissingAttributeError(`response`, "users"))
	}
	if err2 := mt.Users.Validate(); err2 != nil {
		err = goa.MergeErrors(err, err2)
	}
	return
}

// user (default view)
//
// Identifier: application/vnd.user+json; view=default
type User struct {
	// Date of creation
	CreatedAt time.Time `form:"created_at" json:"created_at" xml:"created_at"`
	// ID of user
	ID int `form:"id" json:"id" xml:"id"`
	// Name of user
	Name string `form:"name" json:"name" xml:"name"`
}

// Validate validates the User media type instance.
func (mt *User) Validate() (err error) {

	if mt.Name == "" {
		err = goa.MergeErrors(err, goa.MissingAttributeError(`response`, "name"))
	}

	return
}

// UserCollection is the media type for an array of User (default view)
//
// Identifier: application/vnd.user+json; type=collection; view=default
type UserCollection []*User

// Validate validates the UserCollection media type instance.
func (mt UserCollection) Validate() (err error) {
	for _, e := range mt {
		if e != nil {
			if err2 := e.Validate(); err2 != nil {
				err = goa.MergeErrors(err, err2)
			}
		}
	}
	return
}
