// Code generated by goagen v1.3.1, DO NOT EDIT.
//
// API "gateway": Application User Types
//
// Command:
// $ goagen
// --design=github.com/azihsoyn/goa_microservice_sample/gateway/design
// --notest=true
// --notool=true
// --out=$(GOPATH)/src/github.com/azihsoyn/goa_microservice_sample/gateway
// --version=v1.3.1

package app
