// Code generated by goagen v1.3.1, DO NOT EDIT.
//
// API "gateway": gateway Resource Client
//
// Command:
// $ goagen
// --design=github.com/azihsoyn/goa_microservice_sample/gateway/design
// --notest=true
// --notool=true
// --out=$(GOPATH)/src/github.com/azihsoyn/goa_microservice_sample/gateway
// --version=v1.3.1

package client

import (
	"context"
	"fmt"
	"net/http"
	"net/url"
)

// GatewayGatewayPath computes a request path to the gateway action of gateway.
func GatewayGatewayPath() string {

	return fmt.Sprintf("/gateway")
}

// gateway
func (c *Client) GatewayGateway(ctx context.Context, path string) (*http.Response, error) {
	req, err := c.NewGatewayGatewayRequest(ctx, path)
	if err != nil {
		return nil, err
	}
	return c.Client.Do(ctx, req)
}

// NewGatewayGatewayRequest create the request corresponding to the gateway action endpoint of the gateway resource.
func (c *Client) NewGatewayGatewayRequest(ctx context.Context, path string) (*http.Request, error) {
	scheme := c.Scheme
	if scheme == "" {
		scheme = "http"
	}
	u := url.URL{Host: c.Host, Scheme: scheme, Path: path}
	req, err := http.NewRequest("GET", u.String(), nil)
	if err != nil {
		return nil, err
	}
	return req, nil
}
